name: Test Go

on:  
  schedule:
    - cron: '0 */1 * * *'
  pull_request:
    branches: [ main ]
    paths:
      - 'go/**'
  workflow_dispatch:
  
env:
  FORESIGHT_UPLOADER_SIGNER_URL: https://upload.service.runforesight.us
  WORKFLOW_TELEMETRY_BASE_URL: https://api.service.runforesight.us
  
concurrency:
  group: ci-go-tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Go tests
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-22.04, windows-latest]
        dolt_fmt: [ "__DOLT__", "__LD_1__" ]
        include:
          - os: "ubuntu-22.04"
            dolt_fmt: "__DOLT_DEV__"
    steps:
    - name: Collect Workflow Telemetry
      if: always()
      uses: runforesight/foresight-workflow-kit-action@v1
      with:
        api_key: ${{ secrets.FORESIGHT_PROJECT_WALL_APIKEY }}
    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ^1.19
      id: go
    - uses: actions/checkout@v3
    - name: Test All
      working-directory: ./go
      run: |
        files=$(go list ./...)
        SAVEIFS=$IFS
        IFS=$'\n'
        file_arr=($files)
        IFS=$SAVEIFS
        mkdir reports
        for (( i=0; i<${#file_arr[@]}; i++ ))
        do
          echo "Testing Package: ${file_arr[$i]}"
          if [ "$MATRIX_OS" == 'ubuntu-22.04' ]
          then
            if [[ "${file_arr[$i]}" != *enginetest* ]]; then
              go test -v -json -timeout 45m -race "${file_arr[$i]}" > ./reports/test-report-$i.json -coverprofile=coverage.out
            else
              echo "skipping enginetests for -race"
            fi
          else
            go test -v -json -timeout 45m "${file_arr[$i]}" > ./reports/test-report-$i.json -coverprofile=coverage.out
          fi
          succeeded=$(echo "$?")
          if [ "$succeeded" -ne 0 ]; then
            echo "Testing failed in package ${file_arr[$i]}"
            exit 1;
          fi
        done
      env:
        MATRIX_OS: ${{ matrix.os }}
        DOLT_DEFAULT_BIN_FORMAT: ${{ matrix.dolt_fmt }}
    - name: Analyze Test and/or Coverage Results
      if: always()
      uses: runforesight/foresight-test-kit-action@v1
      with:
        working_directory: ./go
        api_key: ${{ secrets.FORESIGHT_PROJECT_WALL_APIKEY }}
        test_framework: golang
        test_format: json
        test_path: ./reports/**
        coverage_format: golang
        coverage_path: |
            coverage.out
  noracetest:
    name: Go tests - no race
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-22.04, windows-latest]
        dolt_fmt: [ "__DOLT__", "__LD_1__" ]
        include:
          - os: "ubuntu-22.04"
            dolt_fmt: "__DOLT_DEV__"
    steps:
    - name: Collect Workflow Telemetry
      if: always()
      uses: runforesight/foresight-workflow-kit-action@v1
      with:
        api_key: ${{ secrets.FORESIGHT_PROJECT_WALL_APIKEY }}
    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ^1.19
      id: go
    - uses: actions/checkout@v3
    - name: Test All
      working-directory: ./go
      run: |
        mkdir reports
        if [ -n "$DOLT_FMT" ]; then export DOLT_DEFAULT_BIN_FORMAT="$DOLT_FMT"; fi
        go test -v -json -timeout 30m ./libraries/doltcore/sqle/altertests > ./reports/test-report-altertests.json -coverprofile=coverage.out
        go test -v -json -timeout 30m ./libraries/doltcore/sqle/integration_test > ./reports/test-report-integration.json -coverprofile=coverage.out
      env:
        DOLT_FMT: ${{ matrix.dolt_fmt }}
        MATRIX_OS: ${{ matrix.os }}
        DOLT_TEST_RUN_NON_RACE_TESTS: "true"
    - name: Analyze Test and/or Coverage Results
      if: always()
      uses: runforesight/foresight-test-kit-action@v1
      with:
        working_directory: ./go
        api_key: ${{ secrets.FORESIGHT_PROJECT_WALL_APIKEY }}
        test_framework: golang
        test_format: json
        test_path: ./reports/**
        coverage_format: golang
        coverage_path: |
            coverage.out
