name: sql-server Integration Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - 'go/**'
      - 'integration-tests/go-sql-server-driver/**'
      
env:
  FORESIGHT_UPLOADER_SIGNER_URL: https://upload.service.runforesight.us
  WORKFLOW_TELEMETRY_BASE_URL: https://api.service.runforesight.us

concurrency:
  group: ci-sql-server-integration-tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: sql-server Integration Tests
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:  [ ubuntu-22.04, macos-latest ] # [ ubuntu-22.04, macos-latest, windows-latest ]
        dolt_fmt: [ "__DOLT__", "__LD_1__" ]
        exclude:
          - os: "macos-latest"
            dolt_fmt: ["__LD_1__" ]
          - os: "windows-latest"
            dolt_fmt: ["__LD_1__" ]
    steps:
      - name: Collect Workflow Telemetry
        if: always()
        uses: runforesight/foresight-workflow-kit-action@v1
        with:
          api_key: ${{ secrets.FORESIGHT_PROJECT_WALL_APIKEY }}
      - name: Setup Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19
        id: go
      - name: Create CI Bin
        run: |
          mkdir -p ./.ci_bin
      - uses: actions/checkout@v3
      - name: Install Dolt
        working-directory: ./go
        run: |
          go build -mod=readonly -o ../.ci_bin/dolt ./cmd/dolt/
      - name: Test all
        env:
          DOLT_FMT: ${{ matrix.dolt_fmt }}
        run: |
          if [ -n "$DOLT_FMT" ]; then export DOLT_DEFAULT_BIN_FORMAT="$DOLT_FMT"; fi
          export DOLT_BIN_PATH="$(pwd)/../../.ci_bin/dolt"
          go test -v -json . > ./test-report.json -coverprofile=coverage.out
        working-directory: ./integration-tests/go-sql-server-driver
      - name: Analyze Test and/or Coverage Results
        if: always()
        uses: runforesight/foresight-test-kit-action@v1
        with:
          working_directory: ./integration-tests/go-sql-server-driver
          api_key: ${{ secrets.FORESIGHT_PROJECT_WALL_APIKEY }}
          test_framework: golang
          test_format: json
          test_path: ./test-report.json
          coverage_format: golang
          coverage_path: |
              coverage.out
